services:
  grafana-lgtm:
    image: 'grafana/otel-lgtm:latest'
    ports:
      - '3000:3000'
      - '4317'
      - '4318'
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432'
  redis:
    image: 'redis:latest'
    ports:
      - '6379'
  kafka:
    image: 'apache/kafka:latest'
    environment:
      - 'KAFKA_NODE_ID=1'
      - 'KAFKA_PROCESS_ROLES=broker,controller'
      - 'KAFKA_LISTENERS=PLAINTEXT://:9092,PLAINTEXT_HOST://:29092,CONTROLLER://:9093'
      - 'KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092'
      - 'KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER'
      - 'KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      - 'KAFKA_CONTROLLER_QUORUM_VOTERS=1@localhost:9093'
      - 'KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1'
      - 'CLUSTER_ID=MkU3OEVBNTcwNTJENDM2Qk'
      - 'KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT'
    ports:
      - '29092:29092'
  schema-registry:
    image: 'confluentinc/cp-schema-registry:7.8.0'
    depends_on:
      - kafka
    environment:
      - 'SCHEMA_REGISTRY_HOST_NAME=schema-registry'
      - 'SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS=kafka:9092'
      - 'SCHEMA_REGISTRY_LISTENERS=http://0.0.0.0:8081'
    ports:
      - '8081:8081'
